### PR TITLE
update requirements

### PR DESCRIPTION
**Pull request by sjsrey**
I think these are it for dependencies (the listed ones would pull in scipy and numpy on install).

### CODE REVIEW

**Comment by yogabonito** [comment]
Thanks for your effort, @sjsrey!
In my docs-branch I have a `setup.py` file with [even more dependencies](https://github.com/yogabonito/region/blob/docs/setup.py#L69). Are `sklearn` and `pytest` also requirements of the packages you listed? If yes, I will merge your PR immediately, otherwise it would be good to include them in the list.

BTW I plan to include the `setup.py` and `requirements.txt` from my docs-branch soon. After my graduation in October I would like to add Travis-CI and documentation to `region`.

**Comment by ljwolf** [comment]
@yogabonito has this been resolved? having merged #5, can we close?

**Comment by yogabonito** [comment]
Having read PySAL's and other projects' docs I think it suffices to have the requirements in setup.py. What do you think, @sjsrey @ljwolf?
Meanwhile I have also added the license to the docs. The corresponding PR will come soon.

**Comment by ljwolf** [comment]
ping?

**Comment by yogabonito** [comment]
No problem, I didn't tell you (I didn't want to bother you with these details) ;)
I didn't think of conda but I will give it a try once I face similar problems again. For now, I think we can leave .travis.yml as it is as I'm sitting in the train headed towards holidays :)

**Pull request merged**
